language: go

go:
  1.7.4

before_install:
  - go get github.com/mattn/goveralls
  - cd $GOPATH/src/github.com/Aerathis/sciuromorpha/vendor/github.com/libgit2/git2go && git submodule update --init && make install
  
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

