language: go

go:
  1.7.4

before_install:
  - go get github.com/mattn/goveralls
  - go get -d github.com/libgit2/git2go && cd $GOPATH/src/github.com/libgit2/git2go && git submodule update --init && make install
  
script:
  - cd $GOPATH/src/github.com/Aerathis/sciuromorpha && $HOME/gopath/bin/goveralls -service=travis-ci

